### ISSUE TITLE
Error in type definitions

### ISSUE THREAD

**Issue by dubisdev** [abdmmar/wc-toast#15]
Hi @abdmmar , thanks for this amazing component.

I'm trying to use this in a personal project with TypeScript and I just saw there is an error with the type definitions.

![image](https://user-images.githubusercontent.com/77246331/198330447-823c3397-f501-48f6-84fc-e665788be728.png)

The component continues working but TS shows an error because the types file might be incorrect.

If you need it, I could try to open a PR to fix this.

**Comment by abdmmar** [comment]
Thanks @dubisdev, please send us a PR if you got some freetime. ❤️
