### ISSUE TITLE
import error on TypeScript 5.1.0

### ISSUE THREAD

**Issue by aztack** [abdmmar/wc-toast#18]
<img width="940" alt="image" src="https://user-images.githubusercontent.com/782871/233934437-221617d9-eaff-4299-865b-f425e7a1e241.png">

**Comment by abdmmar** [comment]
Hi @aztack, sorry for the delayed response. I've been pretty caught up with other stuff lately and haven't had a chance to dig into your report. I'll try to look into it, thanks!
