### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by alexolliveira** [abdmmar/wc-toast#26]
Hi! I would like to implement wc-toast on my website... but I only know to use like this:<script src="file.js"></script>. Can you help me?

**Comment by abdmmar** [comment]
Hey @alexolliveira, appreciate you trying out `wc-toast`!

I've just updated the example on using `wc-toast` with the `<script>` tag. Check it out here: https://github.com/abdmmar/wc-toast/tree/main/examples/wc-toast-script.

Essentially, you include `wc-toast` with the `<script>` tag. Import the `toast` from `./src/wc-toast` and don't forget to add `type="module"` to your script tag for proper loading of `wc-toast`. If you've already set it up, you can refer to the [basic usage](https://github.com/abdmmar/wc-toast?tab=readme-ov-file#basic-usage) section on how to use it. Cheers!
