### ISSUE TITLE
Module parse failed: Unexpected token (55:40)

### ISSUE THREAD

**Issue by DevGoatX** [abdmmar/wc-toast#9]
Hi, I use node version 16.0 in React project.
I was trying to add wc-toast.
I added <wc-toast position="top-center"> </wc-toast> in the body tag of public/index.html file.
And I imported toast
import { toast } from 'wc-toast';

But I got failed and got issues.

Failed to compile.

```
./node_modules/wc-toast/src/toast.js 55:40
Module parse failed: Unexpected token (55:40)
You may need an appropriate loader to handle this file type.
|   toastItem.setAttribute('duration', duration ? duration : '');
|   toastItem.setAttribute('data-toast-item-id', id);
>   toastItem.setAttribute('theme', theme?.type ? theme.type : 'light');
| 
|   if (theme?.type === 'custom' && theme?.style) {
```

Please let me know how to fix this issue.
Thanks in advance.
Regards

**Comment by abdmmar** [comment]
Thanks for opening the issue and I'm really sorry if it's too late to reply. 

I guess your error is related to your bundler/babel configuration and not with `wc-toast`.

See: 
- https://github.com/babel/babel-loader/issues/173
- https://stackoverflow.com/questions/63769414/react-module-parse-failed-unexpected-token-you-may-need-an-appropriate-loade
